### ISSUE TITLE
$Murder ???

### ISSUE THREAD

**Issue by NolikTop** [ZPlayzMCPE/SkyClashsPE#1]
https://github.com/ZPlayzMCPE/SkyClashsPE/blob/master/src/PocketMiner/SkyWars/SkyClashsPE.php#L111
So, do you see the var $Murder? 
But this var never been initialized

**Comment by ZPlayzMCPE** [comment]
I'll see if I can fix it. Thanks for the spot.

**Comment by ZPlayzMCPE** [comment]
Okay, should be fixed.
